### ISSUE TITLE
W/InputMethodManager(13869): The current service view is not the focus view

### ISSUE THREAD

**Issue by nickolaylo** [qiuxiang/flutter-android-window#11]
Thank you for this awesome plugin, my current issue is that the keyboard does not appear when I select any TextField widgets used to collect user input instead of plain Text, I am testing using my Huawei P20 Lite, this is the error I get:

W/InputMethodManager(32690): The current service view is not the focus view

**Comment by qiuxiang** [comment]
I also found this problem but there is no solution for now

**Comment by nickolaylo** [comment]
> I also found this problem but there is no solution for now

Thank you for replying, in order for the window to get key input focus, This is the solution we must implement to enable the Keyboard [Click Here](https://localazy.com/blog/floating-windows-on-android-6-keyboard-input), unfortunately, I have no Kotlin background; I am struggling with it 2 weeks now, maybe if you have java or Kotlin background you can fix it, [Here](https://www.geeksforgeeks.org/how-to-make-a-floating-window-application-in-android/) another project fixing the problem, Could you please look at those solutions and try implementing it ?

**Comment by nickolaylo** [comment]
> I also found this problem but there is no solution for now

Maybe It would be easier to use this [Flutter plugin](https://pub.dev/packages/flutter_windowmanager) for manipulating Android WindowManager LayoutParams dynamically at application run-time, WindowManager used at solutions I provided in my previous comment; I will let you know if I fix it, I would appreciate any little help, Thank you

**Comment by qiuxiang** [comment]
u can try the new version v0.1.1

add `focusable: true` to `open()`:
https://github.com/qiuxiang/flutter-android-window/blob/bd2fd41d924037126bfc95fb56320f11b9e5cc4b/example/lib/main.dart#L55

**Comment by nickolaylo** [comment]
> u can try the new version v0.1.1
> 
> add `focusable: true` to `open()`:
> 
> https://github.com/qiuxiang/flutter-android-window/blob/bd2fd41d924037126bfc95fb56320f11b9e5cc4b/example/lib/main.dart#L55

Thank you so much, Oh my God it's working, You are a hero 🌹
