### ISSUE TITLE
大哥知道这是什么问题吗？

### ISSUE THREAD

**Issue by DarkReunion** [qiuxiang/flutter-android-window#16]
百度的不管用，挂梯子也试过
![屏幕截图 2022-05-09 145548](https://user-images.githubusercontent.com/45262812/167356585-b249755d-645b-4424-b8be-f29e77ff40c5.png)

**Comment by qiuxiang** [comment]
基本上就是梯子的问题

**Comment by DarkReunion** [comment]
> 基本上就是梯子的问题

我把梯子关了，重启了一下，也还是这个错误😭
