### ISSUE TITLE
debug能正常使用，release会报错

### ISSUE THREAD

**Issue by VenusCao** [qiuxiang/flutter-android-window#19]
![QQ图片20220518094656](https://user-images.githubusercontent.com/25027947/168940674-bc69ace5-9288-4b32-990b-12c1c105315a.png)

**Comment by qiuxiang** [comment]
暂时看不出来什么问题，最好能提供一个可以重现这个错误的 demo 项目

**Comment by VenusCao** [comment]
测试了下只要加上 url_launcher 插件，release就会报这个错，不加就没有

**Comment by VenusCao** [comment]
升级flutter3.0.0就好了

**Comment by cnyunguo** [comment]
[](url)

> 暂时看不出来什么问题，最好能提供一个可以重现这个错误的 demo 项目

这个问题确实存在，我贴出了log，并且是较严重的问题，我贴出了log，希望可以有解决办法。
E/flutter (17069): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'androidWindow' declared.
E/flutter (17069): Receiver: top-level
E/flutter (17069): Tried calling: androidWindow, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:222)
E/flutter (17069):
E/flutter (17069): [ERROR:flutter/runtime/dart_isolate.cc(681)] Could not resolve main entrypoint function.
E/flutter (17069): [ERROR:flutter/runtime/dart_isolate.cc(165)] Could not run the run main Dart entrypoint.
E/flutter (17069): [ERROR:flutter/runtime/runtime_controller.cc(381)] Could not create root isolate.
E/flutter (17069): [ERROR:flutter/shell/common/shell.cc(580)] Could not launch engine with configuration.
