### ISSUE TITLE
想获取悬浮窗的坐标位置

### ISSUE THREAD

**Issue by WeiCJ2020** [qiuxiang/flutter-android-window#22]
想整一个自动贴边的功能，但是不知道怎么获取悬浮窗的位置坐标。
以前没有接触过移动开发，翻看源码发现里面有DragEnd事件，大哥是有打算整自动贴边的功能么:smile:

**Comment by qiuxiang** [comment]
没打算做自动贴边，这最好在原生里实现，控制移动是在原生里做的，位置信息就已经存有了

**Comment by WeiCJ2020** [comment]
> 没打算做自动贴边，这最好在原生里实现，控制移动是在原生里做的，位置信息就已经存有了

好的,非常感谢。有空我学一下之后试着在原生里面实现一下
