### ISSUE TITLE
在悬浮窗上关闭悬浮窗报错

### ISSUE THREAD

**Issue by zzzhhhhh001** [qiuxiang/flutter-android-window#23]
我把例子放在我自己的工程里跑，可以成功显示悬浮窗，但是点悬浮窗上的关闭按钮就会报错，并且直接关闭我的程序，报错如图
![IMG_20230303_141756](https://user-images.githubusercontent.com/104045958/222646886-9e6d8256-9658-4ddc-a9d8-fb1e23119cb7.jpg)

**Comment by qiuxiang** [comment]
我周末处理下

**Comment by zzzhhhhh001** [comment]
是插件的错误么，我新建项目跑例子是正常的，我以为是我项目的问题

**Comment by qiuxiang** [comment]
不知道为什么，engine destroy 的时候出错了，我需要看看什么情况下会出错，如果什么都不管，加个 try catch 也能避免 app 崩掉。

**Comment by zzzhhhhh001** [comment]
补充一个，在程序中用android_windows.close()也会崩溃。
发一个收款码吧，请大佬喝被奶茶

**Comment by qiuxiang** [comment]
![image](https://user-images.githubusercontent.com/1709072/222658802-d3954712-2f02-404a-a5fb-d0a7adf506fa.png)

**Comment by qiuxiang** [comment]
先确认下，Application 改了吗
```
class MainApplication : qiuxiang.android_window.AndroidWindowApplication()
```

**Comment by zzzhhhhh001** [comment]
改了的
有MainApplication这个文件，内容跟readme里的一模一样，Mainiftest里也添加了android:name=".MainApplication"
悬浮窗是可以正常显示的
本来想发图片的，但是太大了被退回了

**Comment by zzzhhhhh001** [comment]
我试了一下0.3.3版本的插件还是会关闭程序

**Comment by zzzhhhhh001** [comment]
好用了，感谢
