### ISSUE TITLE
Usage of other plugins?

### ISSUE THREAD

**Issue by princesanjivy** [qiuxiang/flutter-android-window#6]
Firstly, this is a great pluign I came across and it suits prefectly for my need. I am wondering whether it is possible to use all other plugins out there normally as using in Flutter projects, because no external plugin worked inside androidWindow() eg. the plugins which I tested out 

- camera
- url_launcher
- http

If its possible to use, please do share some hints or references.

**Comment by qiuxiang** [comment]
It can be clear that url_launcher is not supported. And other plugins that rely activity also not work. Because floating window run as service not activity.

http should work. I'll write a example for it later.
